<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="pt-br">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">875b4c44898cae512f08f519a38456c5814427a0</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.StackOverflowException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">2da0d4e7a795b7a3f9d9ea9c1bdb5e575688522d</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">9a2a773c3505724e59b782c1b78a9bea12abec17</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown when the execution stack overflows because it contains too many nested method calls.</source>
          <target state="translated">A exceção que é lançada quando a pilha de execução excede porque ele contém um número excessivo de chamadas de método aninhadas.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve">
          <source>This class cannot be inherited.</source>
          <target state="translated">Essa classe não pode ser herdada.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT">
          <source>StackOverflowException is thrown for execution stack overflow errors, typically in case of a very deep or unbounded recursion.</source>
          <target state="translated">StackOverflowException é lançada para erros de estouro de pilha de execução, normalmente em caso de recursão muito profunda ou não vinculada.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT">
          <source>StackOverflowException uses the HRESULT COR_E_STACKOVERFLOW, which has the value 0x800703E9.</source>
          <target state="translated">StackOverflowException usa o HRESULT COR_E_STACKOVERFLOW, que tem o valor 0x800703E9.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT">
          <source>The &lt;xref:System.Reflection.Emit.OpCodes.Localloc&gt; intermediate language (IL) instruction throws StackOverflowException.</source>
          <target state="translated">O &lt;xref:System.Reflection.Emit.OpCodes.Localloc&gt;instrução de linguagem intermediária (IL) gera StackOverflowException.&lt;/xref:System.Reflection.Emit.OpCodes.Localloc&gt;</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT">
          <source>For a list of initial property values for a StackOverflowException object, see the &lt;xref:System.StackOverflowException.%23ctor%2A&gt; constructors.</source>
          <target state="translated">Para obter uma lista de valores de propriedade inicial de um objeto StackOverflowException, consulte o &lt;xref:System.StackOverflowException.%23ctor%2A&gt;construtores.&lt;/xref:System.StackOverflowException.%23ctor%2A&gt;</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" extradata="MT">
          <source>Version Considerations    In the .NET Framework 1.0 and 1.1, you could catch a StackOverflowException object (for example, to recover from unbounded recursion).</source>
          <target state="translated">Considerações sobre a versão do .NET Framework 1.0 e 1.1, você pode capturar um objeto StackOverflowException (por exemplo, para se recuperar de recursão ilimitada).</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" extradata="MT">
          <source>Starting with the .NET Framework 2.0, you can’t catch a StackOverflowException object with a <ph id="ph1">`try`</ph><ph id="ph2">/</ph><ph id="ph3">`catch`</ph> block, and the corresponding process is terminated by default.</source>
          <target state="translated">Começando com o .NET Framework 2.0, você não pode pegar um objeto StackOverflowException com um <ph id="ph1">`try`</ph> <ph id="ph2">/</ph> <ph id="ph3">`catch`</ph> bloco e o processo correspondente será finalizado por padrão.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT">
          <source>Consequently, you should write your code to detect and prevent a stack overflow.</source>
          <target state="translated">Consequentemente, você deve escrever seu código para detectar e prevenir um estouro de pilha.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" extradata="MT">
          <source>For example, if your app depends on recursion, use a counter or a state condition to terminate the recursive loop.</source>
          <target state="translated">Por exemplo, se seu aplicativo depende de recursão, use uma condição de estado ou de um contador para encerrar o loop recursivo.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following example uses a counter to ensure that the number of recursive calls to the <ph id="ph1">`Execute`</ph> method do not exceed a maximum defined by the MAX_RECURSIVE_CALLS constant.</source>
          <target state="translated">O exemplo a seguir usa um contador para garantir que o número de recursiva chamadas para o <ph id="ph1">`Execute`</ph> método não exceder o máximo definido pela constante MAX_RECURSIVE_CALLS.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" extradata="MT">
          <source><bpt id="p1">[!code-vb</bpt><bpt id="p2">[</bpt>System.StackOverflowException.Class#1<ept id="p2">](~/add/codesnippet/visualbasic/t-system.stackoverflowex_1.vb)</ept><ept id="p1">]</ept>  <bpt id="p3">[!code-cs</bpt><bpt id="p4">[</bpt>System.StackOverflowException.Class#1<ept id="p4">](~/add/codesnippet/csharp/t-system.stackoverflowex_1.cs)</ept><ept id="p3">]</ept><ph id="ph1">      &gt; </ph><ph id="ph2">[!NOTE]</ph> &gt;  Applying the &lt;xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute&gt; attribute to a method that throws a StackOverflowException has no effect.</source>
          <target state="translated"><bpt id="p1">[!code-vb</bpt><bpt id="p2">[</bpt>System.StackOverflowException.Class#1<ept id="p2">](~/add/codesnippet/visualbasic/t-system.stackoverflowex_1.vb)</ept><ept id="p1">]</ept><bpt id="p3">[!code-cs</bpt><bpt id="p4">[</bpt>System.StackOverflowException.Class#1<ept id="p4">](~/add/codesnippet/csharp/t-system.stackoverflowex_1.cs)</ept> <ept id="p3">]</ept> <ph id="ph1">      &gt; </ph> <ph id="ph2">[!NOTE]</ph> &gt; aplicando o &lt;xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute&gt;atributo para um método que gera uma StackOverflowException não tem nenhum efeito.&lt;/xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute&gt;  </target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" extradata="MT">
          <source>You still cannot handle the exception from user code.</source>
          <target state="translated">Você não pode manipular a exceção do código do usuário.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" extradata="MT">
          <source>If your app hosts the common language runtime (CLR), it can specify that the CLR should unload the application domain where the stack overflow exception occurs and let the corresponding process continue.</source>
          <target state="translated">Se seu aplicativo hospeda o common language runtime (CLR), pode especificar que o CLR deve descarregar o domínio de aplicativo onde a exceção de estouro de pilha ocorre e permitir que o processo correspondente continue.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT">
          <source>For more information, see <bpt id="p1">[</bpt>ICLRPolicyManager Interface<ept id="p1">](~/add/includes/ajax-current-ext-md.md)</ept>.</source>
          <target state="translated">Para obter mais informações, consulte <bpt id="p1">[</bpt>ICLRPolicyManager Interface<ept id="p1">](~/add/includes/ajax-current-ext-md.md)</ept>.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.StackOverflowException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class, setting the &lt;xref:System.Exception.Message*&gt; property of the new instance to a system-supplied message that describes the error, such as "The requested operation caused a stack overflow."</source>
          <target state="translated">Inicializa uma nova instância do <bpt id="p1">&lt;xref href="System.StackOverflowException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> classe, definindo a &lt;xref:System.Exception.Message*&gt;propriedade da nova instância para uma mensagem fornecida pelo sistema que descreve o erro, como "a operação solicitada causou um estouro de pilha."&lt;/xref:System.Exception.Message*&gt;</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve">
          <source>This message takes into account the current system culture.</source>
          <target state="translated">Esta mensagem leva em conta a cultura atual do sistema.</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.StackOverflowException&gt;.</source>
          <target state="translated">A tabela a seguir mostra os valores de propriedade inicial para uma instância de &lt;xref:System.StackOverflowException&gt;.&lt;/xref:System.StackOverflowException&gt;</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The localized error message string.|</source>
          <target state="translated">| Propriedade | Valor |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| <ph id="ph1">`null`</ph>.|   | &lt;xref:System.Exception.Message%2A&gt;| A cadeia de caracteres de mensagem de erro localizada. |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.StackOverflowException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message.</source>
          <target state="translated">Inicializa uma nova instância do <bpt id="p1">&lt;xref href="System.StackOverflowException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> classe com uma mensagem de erro especificada.</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.StackOverflowException&gt;.</source>
          <target state="translated">A tabela a seguir mostra os valores de propriedade inicial para uma instância de &lt;xref:System.StackOverflowException&gt;.&lt;/xref:System.StackOverflowException&gt;</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|A null reference (<ph id="ph1">`Nothing`</ph> in Visual Basic).|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">| Propriedade | Valor |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| Uma referência nula (<ph id="ph1">`Nothing`</ph> no Visual Basic). |   | &lt;xref:System.Exception.Message%2A&gt;| A cadeia de caracteres de mensagem de erro. |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve">
          <source>A &lt;xref:System.String&gt; that describes the error.</source>
          <target state="translated">Um &lt;xref:System.String&gt;que descreve o erro.&lt;/xref:System.String&gt;</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve">
          <source>The content of message is intended to be understood by humans.</source>
          <target state="translated">O conteúdo da mensagem deve ser compreendido por humanos.</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve">
          <source>The caller of this constructor is required to ensure that this string has been localized for the current system culture.</source>
          <target state="translated">O chamador desse construtor é necessário para garantir que essa cadeia de caracteres foi localizada para a cultura atual do sistema.</target>       </trans-unit>
        <trans-unit id="126" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.StackOverflowException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">Inicializa uma nova instância do <bpt id="p1">&lt;xref href="System.StackOverflowException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> classe com uma mensagem de erro especificada e uma referência à exceção interna que é a causa dessa exceção.</target>       </trans-unit>
        <trans-unit id="127" translate="yes" xml:space="preserve" extradata="MT">
          <source>An exception that is thrown as a direct result of a previous exception can include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">Uma exceção que é lançada como um resultado direto de uma exceção anterior pode incluir uma referência à exceção anterior no &lt;xref:System.Exception.InnerException%2A&gt;propriedade.&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="128" translate="yes" xml:space="preserve" extradata="MT">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or a null reference (<ph id="ph1">`Nothing`</ph> in Visual Basic) if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">O &lt;xref:System.Exception.InnerException%2A&gt;propriedade retorna o mesmo valor que é passado para o construtor, ou uma referência nula (<ph id="ph1">`Nothing`</ph> no Visual Basic) se o &lt;xref:System.Exception.InnerException%2A&gt;propriedade não fornecer o valor da exceção interna para o construtor.&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="129" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.StackOverflowException&gt;.</source>
          <target state="translated">A tabela a seguir mostra os valores de propriedade inicial para uma instância de &lt;xref:System.StackOverflowException&gt;.&lt;/xref:System.StackOverflowException&gt;</target>       </trans-unit>
        <trans-unit id="130" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">| Propriedade | Valor |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| A referência à exceção interna. |   | &lt;xref:System.Exception.Message%2A&gt;| A cadeia de caracteres de mensagem de erro. |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="131" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">A mensagem de erro que explica o motivo da exceção.</target>       </trans-unit>
        <trans-unit id="132" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">A exceção que é a causa da exceção atual.</target>       </trans-unit>
        <trans-unit id="133" translate="yes" xml:space="preserve">
          <source>If the <ph id="ph1">`innerException`</ph> parameter is not a null reference (<bpt id="p1">&lt;xref uid="langword_csharp_Nothing" name="Nothing" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> in Visual Basic), the current exception is raised in a <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> block that handles the inner exception.</source>
          <target state="translated">Se o <ph id="ph1">`innerException`</ph> parâmetro não é uma referência nula (<bpt id="p1">&lt;xref uid="langword_csharp_Nothing" name="Nothing" href=""&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> no Visual Basic), a exceção atual é gerada em um <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt> <ept id="p2">&lt;/xref&gt;</ept> bloco que manipula a exceção interna.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>