<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="hu-hu">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">f9a8c40d01b27aa1e33c99da212315550131a5e6</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.AddIn.Hosting.InvalidPipelineStoreException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">8cc811f252afa24d6dbe7ac9e99cfb0e999376df</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">c6b6caa2357931d43d715674fc2665c519b5cc6c</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown when a directory is not found and the user does not have permission to access the pipeline root path or an add-in path.</source>
          <target state="translated">A kivétellel, hogy a könyvtár nem található, és a felhasználó nem rendelkezik hozzáféréssel a feldolgozási sor elérési útjának gyökeréhez vagy a bővítmény elérési útjának vált ki.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT">
          <source>Unlike &lt;xref:System.IO.DirectoryNotFoundException&gt;, this exception does not provide any path information.</source>
          <target state="translated">Eltérően &lt;xref:System.IO.DirectoryNotFoundException&gt;, ez a kivétel nem biztosít Útvonaladatok.&lt;/xref:System.IO.DirectoryNotFoundException&gt;</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT">
          <source>This prevents a malicious user from deliberately specifying erroneous paths and using the information returned by the exception to determine actual paths.</source>
          <target state="translated">Ez megakadályozza, hogy egy rosszindulatú felhasználó szándékosan megadja a hibás, és a kivétel által visszaadott adatok segítségével határozza meg az útvonalakat.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT">
          <source>This exception is thrown by the following discovery methods that build and update the store of add-in and pipeline information: &lt;xref:System.AddIn.Hosting.AddInStore.FindAddIns%2A&gt;,&lt;xref:System.AddIn.Hosting.AddInStore.Rebuild%2A&gt;, &lt;xref:System.AddIn.Hosting.AddInStore.RebuildAddIns%2A&gt;, &lt;xref:System.AddIn.Hosting.AddInStore.Update%2A&gt;, and &lt;xref:System.AddIn.Hosting.AddInStore.UpdateAddIns%2A&gt;.</source>
          <target state="translated">A kivétel a következő felderítési módszerek összeállítása, és frissítse a beépülő modul és a kimenetátirányítási adatot tárol: &lt;xref:System.AddIn.Hosting.AddInStore.FindAddIns%2A&gt;,&lt;xref:System.AddIn.Hosting.AddInStore.Rebuild%2A&gt;, &lt;xref:System.AddIn.Hosting.AddInStore.RebuildAddIns%2A&gt;, &lt;xref:System.AddIn.Hosting.AddInStore.Update%2A&gt;, és &lt;xref:System.AddIn.Hosting.AddInStore.UpdateAddIns%2A&gt;.&lt;/xref:System.AddIn.Hosting.AddInStore.UpdateAddIns%2A&gt; &lt;/xref:System.AddIn.Hosting.AddInStore.Update%2A&gt; &lt;/xref:System.AddIn.Hosting.AddInStore.RebuildAddIns%2A&gt; &lt;/xref:System.AddIn.Hosting.AddInStore.Rebuild%2A&gt; &lt;/xref:System.AddIn.Hosting.AddInStore.FindAddIns%2A&gt;</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.AddIn.Hosting.InvalidPipelineStoreException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class.</source>
          <target state="translated">Egy új példányát inicializálja a <bpt id="p1">&lt;xref href="System.AddIn.Hosting.InvalidPipelineStoreException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> osztály.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.AddIn.Hosting.InvalidPipelineStoreException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with the specified message.</source>
          <target state="translated">Egy új példányát inicializálja a <bpt id="p1">&lt;xref href="System.AddIn.Hosting.InvalidPipelineStoreException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> a megadott üzenet osztályra.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve">
          <source>A description of the error.</source>
          <target state="translated">A hiba leírása.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.AddIn.Hosting.InvalidPipelineStoreException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with serialization and streaming context information.</source>
          <target state="translated">Egy új példányát inicializálja a <bpt id="p1">&lt;xref href="System.AddIn.Hosting.InvalidPipelineStoreException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> a szerializálás és a környezet információt streameléshez osztályt.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT">
          <source>This constructor is called during deserialization to reconstitute an exception object that is transmitted over a stream.</source>
          <target state="translated">Ez a konstruktor nevezik meglévő kölcsönökre adatfolyam során átvitt kivétel objektum deszerializálása közben.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" extradata="MT">
          <source>For more information, see <bpt id="p1">[</bpt>XML and SOAP Serialization<ept id="p1">](~/add/includes/ajax-current-ext-md.md)</ept>.</source>
          <target state="translated">További információkért lásd: <bpt id="p1">[</bpt>XML és a SOAP-szerializálási<ept id="p1">](~/add/includes/ajax-current-ext-md.md)</ept>.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>The serialized object data.</source>
          <target state="translated">A szerializált objektum adatokat.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve">
          <source>The contextual information about the source or destination object data.</source>
          <target state="translated">A cél- és objektum adatok környezetfüggő információit.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.AddIn.Hosting.InvalidPipelineStoreException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with the specified message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">Egy új példányát inicializálja a <bpt id="p1">&lt;xref href="System.AddIn.Hosting.InvalidPipelineStoreException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> osztály a megadott üzenet és a belső kivételben találhatók okozza-e ezt a kivételt, mutató hivatkozás.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" extradata="MT">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">Kivételt vált ki, mert egy előző kivétel közvetlen eredménye tartalmaznia kell egy hivatkozást az előző kivétel az a &lt;xref:System.Exception.InnerException%2A&gt;tulajdonság.&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed to the constructor, or a null reference if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">A &lt;xref:System.Exception.InnerException%2A&gt;tulajdonság a konstruktorban, vagy null hivatkozás. Ha átadott ugyanazt az értéket adja vissza a &lt;xref:System.Exception.InnerException%2A&gt;tulajdonság nem adja meg a belső kivétel értékét a konstruktor.&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of the &lt;xref:System.AddIn.Hosting.AddInSegmentDirectoryNotFoundException&gt; class.</source>
          <target state="translated">Az alábbi táblázat a kezdeti tulajdonságértékek &lt;xref:System.AddIn.Hosting.AddInSegmentDirectoryNotFoundException&gt;osztály&lt;/xref:System.AddIn.Hosting.AddInSegmentDirectoryNotFoundException&gt; példánya</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The localized error message string.|</source>
          <target state="translated">| Tulajdonság |} Érték |}   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| A belső kivétel referencia. |}   | &lt;xref:System.Exception.Message%2A&gt;| Az üzenet honosított hibakarakterlánc. |}&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve">
          <source>A description of the error.</source>
          <target state="translated">A hiba leírása.</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">A kivétellel, hogy a jelenlegi kivétel okozza.</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve">
          <source>If the <ph id="ph1">`innerException`</ph> parameter is not a null reference, the current exception is raised in a catch block that handles the inner exception.</source>
          <target state="translated">Ha a <ph id="ph1">`innerException`</ph> paraméter nem egy null hivatkozás, a jelenlegi kivétel következik be egy catch blokkban, amely kezeli a belső kivételben találhatók.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>