<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="zh-cn">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">257fda0e7c6b22b25ba87f68e5e86cd657c350d2</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.Runtime.Remoting.ServerException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">a45ac4e10b0f593441eef19f784387c74a7ad1f2</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">40c2bfde8b93a379b57be1b992d1aa80188b7eec</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown to communicate errors to the client when the client connects to non-.NET Framework applications that cannot throw exceptions.</source>
          <target state="translated">引发以向客户端传达错误，当客户端连接到无法引发异常的非.NET Framework 应用程序的异常。</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve">
          <source>ServerException uses the HRESULT COR_E_SERVER, which has the value 0x8013150E.</source>
          <target state="translated">ServerException 使用 HRESULT COR_E_SERVER，其值 0x8013150E。</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve">
          <source>ServerException uses the default &lt;xref:System.Object.Equals%2A&gt; implementation, which supports reference equality.</source>
          <target state="translated">ServerException 使用默认&lt;xref:System.Object.Equals%2A&gt;支持引用相等性的实现。&lt;/xref:System.Object.Equals%2A&gt;</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve">
          <source>For a list of initial property values for an instance of ServerException, see the ServerException constructors.</source>
          <target state="translated">ServerException 的实例的初始属性值的列表，请参阅 ServerException 构造函数。</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Runtime.Remoting.ServerException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with default properties.</source>
          <target state="translated">初始化的新实例<bpt id="p1">&lt;xref href="System.Runtime.Remoting.ServerException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>使用默认属性的类。</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve">
          <source>&lt;xref:System.Runtime.Remoting.ServerException&gt; inherits from the &lt;xref:System.SystemException&gt; class.</source>
          <target state="translated">&lt;xref:System.Runtime.Remoting.ServerException&gt;继承&lt;xref:System.SystemException&gt;类。&lt;/xref:System.SystemException&gt;&lt;/xref:System.Runtime.Remoting.ServerException&gt;</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve">
          <source>The following table shows initial property values for an instance of the &lt;xref:System.Runtime.Remoting.ServerException&gt; class:      |Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>|   |&lt;xref:System.Exception.Message%2A&gt;|The empty string ("")|</source>
          <target state="translated">下表显示&lt;xref:System.Runtime.Remoting.ServerException&gt;类的实例的初始属性值: |属性 |值 |  |--------------|-----------|  |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>|  |&lt;xref:System.Exception.Message%2A&gt;|空字符串 ("") |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Runtime.Remoting.ServerException&gt;</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Runtime.Remoting.ServerException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified message.</source>
          <target state="translated">初始化的新实例<bpt id="p1">&lt;xref href="System.Runtime.Remoting.ServerException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>使用指定的消息的类。</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve">
          <source>&lt;xref:System.Runtime.Remoting.ServerException&gt; inherits from the &lt;xref:System.SystemException&gt; class.</source>
          <target state="translated">&lt;xref:System.Runtime.Remoting.ServerException&gt;继承&lt;xref:System.SystemException&gt;类。&lt;/xref:System.SystemException&gt;&lt;/xref:System.Runtime.Remoting.ServerException&gt;</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve">
          <source>The following table shows initial property values for an instance of the &lt;xref:System.Runtime.Remoting.ServerException&gt; class:      |Property Type|Condition|   |-------------------|---------------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>|   |&lt;xref:System.Exception.Message%2A&gt;|The <ph id="ph2">`message`</ph> string|</source>
          <target state="translated">下表显示&lt;xref:System.Runtime.Remoting.ServerException&gt;类的实例的初始属性值: |属性类型 |条件 |  |-------------------|---------------|  |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>|  |&lt;xref:System.Exception.Message%2A&gt;|<ph id="ph2">`message`</ph>字符串 |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Runtime.Remoting.ServerException&gt;</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>The message that describes the exception</source>
          <target state="translated">描述异常的消息</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Runtime.Remoting.ServerException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">初始化的新实例<bpt id="p1">&lt;xref href="System.Runtime.Remoting.ServerException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>使用指定的错误消息和对导致此异常的内部异常的引用的类。</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">前一个异常的直接结果应包含中的前一个异常的引用引发的异常，&lt;xref:System.Exception.InnerException%2A&gt;属性。&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id="ph1">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">&lt;xref:System.Exception.InnerException%2A&gt;属性返回相同的值传递到构造函数中，或<ph id="ph1">`null`</ph>如果&lt;xref:System.Exception.InnerException%2A&gt;属性不会提供给构造函数的内部异常值。&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve">
          <source>The following table shows initial property values for an instance of the &lt;xref:System.Runtime.Remoting.ServerException&gt; class:      |Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string|</source>
          <target state="translated">下表显示&lt;xref:System.Runtime.Remoting.ServerException&gt;类的实例的初始属性值: |属性 |值 |  |--------------|-----------|  |&lt;xref:System.Exception.InnerException%2A&gt;|内部异常引用 |  |&lt;xref:System.Exception.Message%2A&gt;|错误消息字符串 |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Runtime.Remoting.ServerException&gt;</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">解释异常原因的错误消息。</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">导致当前异常的异常。</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve">
          <source>If the <ph id="ph1">`InnerException`</ph> parameter is not <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> block that handles the inner exception.</source>
          <target state="translated">如果<ph id="ph1">`InnerException`</ph>参数不是<bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>中, 引发当前异常<bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept>处理内部异常的块。</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>