<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="ja-jp">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">640459832dd0236167ee0262d7da60da39db8958</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.Runtime.Remoting.RemotingException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">9cca39624fdef7d3456d06ce67436ee38407a925</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">61f6b59e8e1c0fa3089b582298691e975a83589b</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown when something has gone wrong during remoting.</source>
          <target state="translated">リモート処理中に間違った失敗した場合にスローされる例外。</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve">
          <source>RemotingException uses the HRESULT COR_E_REMOTING, which has the value 0x8013150B.</source>
          <target state="translated">RemotingException は、値は 0x8013150B HRESULT COR_E_REMOTING を使用します。</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve">
          <source>RemotingException uses the default &lt;xref:System.Object.Equals%2A&gt; implementation, which supports reference equality.</source>
          <target state="translated">RemotingException が既定値を使用して&lt;xref:System.Object.Equals%2A&gt;参照の等価性をサポートする実装&lt;/xref:System.Object.Equals%2A&gt;。</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve">
          <source>For a list of initial property values for an instance of RemotingException, see the RemotingException constructors.</source>
          <target state="translated">RemotingException のインスタンスの初期プロパティ値の一覧は、RemotingException コンス トラクターを参照してください。</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Runtime.Remoting.RemotingException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with default properties.</source>
          <target state="translated">新しいインスタンスを初期化、 <bpt id="p1">&lt;xref href="System.Runtime.Remoting.RemotingException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>既定のプロパティを持つクラス。</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve">
          <source>&lt;xref:System.Runtime.Remoting.RemotingException&gt; inherits from the &lt;xref:System.SystemException&gt; class.</source>
          <target state="translated">&lt;xref:System.Runtime.Remoting.RemotingException&gt;&lt;xref:System.SystemException&gt;クラス&lt;/xref:System.SystemException&gt;から継承します。&lt;/xref:System.Runtime.Remoting.RemotingException&gt;</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve">
          <source>The following table shows initial property values for an instance of the &lt;xref:System.Runtime.Remoting.RemotingException&gt; class:      |Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>|   |&lt;xref:System.Exception.Message%2A&gt;|The empty string ("")|</source>
          <target state="translated">次の表に、&lt;xref:System.Runtime.Remoting.RemotingException&gt;クラスのインスタンスの初期プロパティ値: |プロパティ |値 |  |--------------|-----------|  |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>|  |&lt;xref:System.Exception.Message%2A&gt;|空の文字列 ("") |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Runtime.Remoting.RemotingException&gt;</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Runtime.Remoting.RemotingException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified message.</source>
          <target state="translated">新しいインスタンスを初期化、 <bpt id="p1">&lt;xref href="System.Runtime.Remoting.RemotingException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>メッセージが指定されたクラスです。</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve">
          <source>&lt;xref:System.Runtime.Remoting.RemotingException&gt; inherits from the &lt;xref:System.SystemException&gt; class.</source>
          <target state="translated">&lt;xref:System.Runtime.Remoting.RemotingException&gt;&lt;xref:System.SystemException&gt;クラス&lt;/xref:System.SystemException&gt;から継承します。&lt;/xref:System.Runtime.Remoting.RemotingException&gt;</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve">
          <source>The following table shows initial property values for an instance of the &lt;xref:System.Runtime.Remoting.RemotingException&gt; class:      |Property Type|Condition|   |-------------------|---------------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>|   |&lt;xref:System.Exception.Message%2A&gt;|The <ph id="ph2">`message`</ph> string|</source>
          <target state="translated">次の表に、&lt;xref:System.Runtime.Remoting.RemotingException&gt;クラスのインスタンスの初期プロパティ値: |プロパティの種類 |条件 |  |-------------------|---------------|  |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>|  |&lt;xref:System.Exception.Message%2A&gt;|<ph id="ph2">`message`</ph>文字列 |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Runtime.Remoting.RemotingException&gt;</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>The error message that explains why the exception occurred.</source>
          <target state="translated">例外が発生した理由を説明するエラー メッセージ。</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Runtime.Remoting.RemotingException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class from serialized data.</source>
          <target state="translated">新しいインスタンスを初期化、 <bpt id="p1">&lt;xref href="System.Runtime.Remoting.RemotingException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>シリアル化されたデータからのクラスです。</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve">
          <source>This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.</source>
          <target state="translated">このコンス トラクターは、ストリームで送信された例外オブジェクトを再構成する逆シリアル化中に呼び出されます。</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>(For more information on serialization, see <bpt id="p1">[</bpt>XML and SOAP Serialization<ept id="p1">](~/add/includes/ajax-current-ext-md.md)</ept>.)</source>
          <target state="translated">(シリアル化の詳細については、次を参照してください<bpt id="p1">[</bpt>XML および SOAP シリアル化<ept id="p1">](~/add/includes/ajax-current-ext-md.md)</ept>。)。</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve">
          <source>The object that holds the serialized object data.</source>
          <target state="translated">シリアル化されたオブジェクト データを保持するオブジェクト。</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve">
          <source>The contextual information about the source or destination of the exception.</source>
          <target state="translated">ソースまたは例外の転送先に関する文脈情報。</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve">
          <source>The <bpt id="p1">&lt;code&gt;</bpt><ph id="ph1">info</ph><ept id="p1">&lt;/code&gt;</ept> parameter is <bpt id="p2">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept>.</source>
          <target state="translated">The <bpt id="p1">&lt;code&gt;</bpt><ph id="ph1">info</ph><ept id="p1">&lt;/code&gt;</ept> parameter is <bpt id="p2">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept>.</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Runtime.Remoting.RemotingException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">新しいインスタンスを初期化、 <bpt id="p1">&lt;xref href="System.Runtime.Remoting.RemotingException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>指定したエラー メッセージおよびこの例外の原因となった内部例外への参照を持つクラス。</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve">
          <source>An exception that is thrown as a direct result of a previous exception will include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">前の例外への参照が含まれます前の例外の直接の結果としてスローされる例外、&lt;xref:System.Exception.InnerException%2A&gt;プロパティ&lt;/xref:System.Exception.InnerException%2A&gt;。</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id="ph1">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">&lt;xref:System.Exception.InnerException%2A&gt;プロパティは、コンス トラクターに渡されたものと同じ値を返しますまたは<ph id="ph1">`null`</ph>場合、&lt;xref:System.Exception.InnerException%2A&gt;プロパティがコンス トラクターには、内部例外値を指定していません&lt;/xref:System.Exception.InnerException%2A&gt;&lt;/xref:System.Exception.InnerException%2A&gt;。</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve">
          <source>The following table shows initial property values for an instance of the &lt;xref:System.Runtime.Remoting.RemotingException&gt; class:      |Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">次の表に、&lt;xref:System.Runtime.Remoting.RemotingException&gt;クラスのインスタンスの初期プロパティ値: |プロパティ |値 |  |--------------|-----------|  |&lt;xref:System.Exception.InnerException%2A&gt;|内部例外の参照 |。  |&lt;xref:System.Exception.Message%2A&gt;|エラー メッセージ文字列 |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Runtime.Remoting.RemotingException&gt; 。</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve">
          <source>The error message that explains why the exception occurred.</source>
          <target state="translated">例外が発生した理由を説明するエラー メッセージ。</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">現在の例外の原因となった例外。</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve">
          <source>If the <ph id="ph1">`InnerException`</ph> parameter is not <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> block that handles the inner exception.</source>
          <target state="translated">場合、<ph id="ph1">`InnerException`</ph>パラメーターではありません<bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>で現在の例外が発生、 <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt> <ept id="p2">&lt;/xref&gt;</ept>ブロックは、内部例外を処理します。</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>