<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="ja-jp">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">257fda0e7c6b22b25ba87f68e5e86cd657c350d2</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.Runtime.Remoting.ServerException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">a45ac4e10b0f593441eef19f784387c74a7ad1f2</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">40c2bfde8b93a379b57be1b992d1aa80188b7eec</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown to communicate errors to the client when the client connects to non-.NET Framework applications that cannot throw exceptions.</source>
          <target state="translated">クライアントが例外をスローできない非 .NET Framework アプリケーションに接続するときにエラーをクライアントに通信するためにスローされる例外。</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve">
          <source>ServerException uses the HRESULT COR_E_SERVER, which has the value 0x8013150E.</source>
          <target state="translated">ServerException は、値は 0x8013150E HRESULT COR_E_SERVER を使用します。</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve">
          <source>ServerException uses the default &lt;xref:System.Object.Equals%2A&gt; implementation, which supports reference equality.</source>
          <target state="translated">ServerException が既定値を使用して&lt;xref:System.Object.Equals%2A&gt;参照の等価性をサポートする実装&lt;/xref:System.Object.Equals%2A&gt;。</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve">
          <source>For a list of initial property values for an instance of ServerException, see the ServerException constructors.</source>
          <target state="translated">ServerException のインスタンスの初期プロパティ値の一覧は、ServerException コンス トラクターを参照してください。</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Runtime.Remoting.ServerException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with default properties.</source>
          <target state="translated">新しいインスタンスを初期化、 <bpt id="p1">&lt;xref href="System.Runtime.Remoting.ServerException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>既定のプロパティを持つクラス。</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve">
          <source>&lt;xref:System.Runtime.Remoting.ServerException&gt; inherits from the &lt;xref:System.SystemException&gt; class.</source>
          <target state="translated">&lt;xref:System.Runtime.Remoting.ServerException&gt;&lt;xref:System.SystemException&gt;クラス&lt;/xref:System.SystemException&gt;から継承します。&lt;/xref:System.Runtime.Remoting.ServerException&gt;</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve">
          <source>The following table shows initial property values for an instance of the &lt;xref:System.Runtime.Remoting.ServerException&gt; class:      |Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>|   |&lt;xref:System.Exception.Message%2A&gt;|The empty string ("")|</source>
          <target state="translated">次の表に、&lt;xref:System.Runtime.Remoting.ServerException&gt;クラスのインスタンスの初期プロパティ値: |プロパティ |値 |  |--------------|-----------|  |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>|  |&lt;xref:System.Exception.Message%2A&gt;|空の文字列 ("") |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Runtime.Remoting.ServerException&gt;</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Runtime.Remoting.ServerException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified message.</source>
          <target state="translated">新しいインスタンスを初期化、 <bpt id="p1">&lt;xref href="System.Runtime.Remoting.ServerException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>メッセージが指定されたクラスです。</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve">
          <source>&lt;xref:System.Runtime.Remoting.ServerException&gt; inherits from the &lt;xref:System.SystemException&gt; class.</source>
          <target state="translated">&lt;xref:System.Runtime.Remoting.ServerException&gt;&lt;xref:System.SystemException&gt;クラス&lt;/xref:System.SystemException&gt;から継承します。&lt;/xref:System.Runtime.Remoting.ServerException&gt;</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve">
          <source>The following table shows initial property values for an instance of the &lt;xref:System.Runtime.Remoting.ServerException&gt; class:      |Property Type|Condition|   |-------------------|---------------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>|   |&lt;xref:System.Exception.Message%2A&gt;|The <ph id="ph2">`message`</ph> string|</source>
          <target state="translated">次の表に、&lt;xref:System.Runtime.Remoting.ServerException&gt;クラスのインスタンスの初期プロパティ値: |プロパティの種類 |条件 |  |-------------------|---------------|  |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>|  |&lt;xref:System.Exception.Message%2A&gt;|<ph id="ph2">`message`</ph>文字列 |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Runtime.Remoting.ServerException&gt;</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>The message that describes the exception</source>
          <target state="translated">例外を説明するメッセージ</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Runtime.Remoting.ServerException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">新しいインスタンスを初期化、 <bpt id="p1">&lt;xref href="System.Runtime.Remoting.ServerException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>指定したエラー メッセージおよびこの例外の原因となった内部例外への参照を持つクラス。</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">前の例外への参照を含める必要があります前の例外の直接の結果としてスローされる例外、&lt;xref:System.Exception.InnerException%2A&gt;プロパティ&lt;/xref:System.Exception.InnerException%2A&gt;。</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id="ph1">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">&lt;xref:System.Exception.InnerException%2A&gt;プロパティは、コンス トラクターに渡されたものと同じ値を返しますまたは<ph id="ph1">`null`</ph>場合、&lt;xref:System.Exception.InnerException%2A&gt;プロパティがコンス トラクターには、内部例外値を指定していません&lt;/xref:System.Exception.InnerException%2A&gt;&lt;/xref:System.Exception.InnerException%2A&gt;。</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve">
          <source>The following table shows initial property values for an instance of the &lt;xref:System.Runtime.Remoting.ServerException&gt; class:      |Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string|</source>
          <target state="translated">次の表に、&lt;xref:System.Runtime.Remoting.ServerException&gt;クラスのインスタンスの初期プロパティ値: |プロパティ |値 |  |--------------|-----------|  |&lt;xref:System.Exception.InnerException%2A&gt;|内部例外を参照 |  |&lt;xref:System.Exception.Message%2A&gt;|エラー メッセージ文字列 |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Runtime.Remoting.ServerException&gt;</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">例外の原因を説明するエラー メッセージ。</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">現在の例外の原因となった例外。</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve">
          <source>If the <ph id="ph1">`InnerException`</ph> parameter is not <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> block that handles the inner exception.</source>
          <target state="translated">場合、<ph id="ph1">`InnerException`</ph>パラメーター <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>で現在の例外が発生、 <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt> <ept id="p2">&lt;/xref&gt;</ept>ブロックは、内部例外を処理します。</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>